language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.4

services:
  - docker

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  - echo "It is before_script"
  dotnet restore

script:
  - echo "It is script"
  dotnet build

after_script:
  - echo "It is after_script"

notifications:
  email:
    recipients:
      omrumbakitemiz@icloud.com
    on_success: never
    on_failure: always 