language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.4

services:
  - docker

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1

before_script:
  dotnet restore

script:
  dotnet build

notifications:
  email:
    recipients:
      omrumbakitemiz@icloud.com
    on_success: never
    on_failure: always 

deploy:
  provider: heroku
  api_key:
    secure: c9d3c534-9490-4e1e-affb-850a03b17c4d
  app: imminoglobulin
  on:
    all_branches: true